server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13326932249
#    这里修改为自己的数据库密码
